package LoginAndRegister;

import Database.Connect_DB;
import Loading.Loading;
import TrangHome.Home;
import TrangHome.ToanCuc;
import java.awt.Font;
import java.sql.Connection;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import java.sql.*;

/**
 *
 * @author ASUS
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Left = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Right = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        EmailTxT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PassTxT = new javax.swing.JPasswordField();
        DangNhap = new javax.swing.JButton();
        btnQuaDangKy = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        Left.setBackground(new java.awt.Color(255, 255, 255));
        Left.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/graduation-cap-256.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(56, 161, 222));
        jLabel5.setText("Quản lý phòng học");

        javax.swing.GroupLayout LeftLayout = new javax.swing.GroupLayout(Left);
        Left.setLayout(LeftLayout);
        LeftLayout.setHorizontalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(23, 23, 23))
        );
        LeftLayout.setVerticalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        jPanel1.add(Left);
        Left.setBounds(0, 0, 400, 500);

        Right.setBackground(new java.awt.Color(255, 255, 255));
        Right.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(56, 161, 222));
        jLabel1.setText("Đăng nhập");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Email:");

        EmailTxT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EmailTxT.setName(""); // NOI18N
        EmailTxT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailTxTActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Mật khẩu:");

        DangNhap.setBackground(new java.awt.Color(56, 161, 222));
        DangNhap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DangNhap.setForeground(new java.awt.Color(255, 255, 255));
        DangNhap.setText("Đăng nhập");
        DangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DangNhapActionPerformed(evt);
            }
        });

        btnQuaDangKy.setBackground(new java.awt.Color(56, 161, 222));
        btnQuaDangKy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQuaDangKy.setForeground(new java.awt.Color(255, 255, 255));
        btnQuaDangKy.setText("Đăng ký");
        btnQuaDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuaDangKyActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setText("Quên mật khẩu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RightLayout = new javax.swing.GroupLayout(Right);
        Right.setLayout(RightLayout);
        RightLayout.setHorizontalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(137, 137, 137))
            .addGroup(RightLayout.createSequentialGroup()
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RightLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(DangNhap)
                        .addGap(40, 40, 40)
                        .addComponent(btnQuaDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RightLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(EmailTxT)
                            .addComponent(jLabel3)
                            .addComponent(PassTxT, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)))
                    .addGroup(RightLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jButton3)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        RightLayout.setVerticalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(EmailTxT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(PassTxT, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuaDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jPanel1.add(Right);
        Right.setBounds(400, 0, 400, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 103, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EmailTxTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTxTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTxTActionPerformed

    
    private void btnQuaDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuaDangKyActionPerformed
      Register register = new Register();
      register.setVisible(true);
      register.pack();
      register.setLocationRelativeTo(null);
      this.dispose();
    }//GEN-LAST:event_btnQuaDangKyActionPerformed

    private void DangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DangNhapActionPerformed
        // TODO add your handling code here:
        Connect_DB cn = new Connect_DB();
        
        
        String email = EmailTxT.getText();
        char[] matKhauChars = PassTxT.getPassword();
        String matKhau = new String(matKhauChars);
        try{
            Connection conn = cn.getConnection();
            if(email.equals("") || matKhauChars.equals("")){
                JOptionPane.showMessageDialog(this,"Bạn phải nhập đủ thông tin");
            }
            else{
                String afteremail = "@gmail.com";
                if(!email.endsWith(afteremail))
                {
                    JOptionPane.showMessageDialog(this,"Email nhập phải có dạng example@gmail.com");
                }
                else{
                    int atIndex = email.indexOf(afteremail);
                    String userName = email.substring(0, atIndex);
                    if(userName.isEmpty()){
                       JOptionPane.showMessageDialog(this,"Email bạn nhập không hợp lệ");
                    }
                    else{
                        if(matKhau.length() < 8 || !matKhau.matches(".*\\d+.*")){
                            JOptionPane.showMessageDialog(this,"Mật khẩu không hợp lệ");
                        }
                        else{
                            String timEmail = "select Email from TaiKhoan where Email= ? And tkpassword=?";
                            PreparedStatement pst = conn.prepareCall(timEmail);
                            pst.setString(1,email);
                            pst.setString(2,matKhau);
                            ResultSet rs = pst.executeQuery();
                            if(rs.next()){
                                JOptionPane.showMessageDialog(this,"Đăng nhập thành công");
                                this.setVisible(false);
                                Loading loading = new Loading();
                                loading.setVisible(true);
                                ToanCuc tt = new ToanCuc();
                                tt.setEmail(email);
                                String accountName = getAccountName(email);
                                tt.setTenTK(accountName);
                            }
                            else{
                                JOptionPane.showMessageDialog(this,"Sai Email hoặc mật khẩu"); 
                            }
                            
                        }
                       }
                }
            }
        } catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "Sai tên tài khoản hoặc mật khẩu");
        }
    }//GEN-LAST:event_DangNhapActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        QuenMK qmk = new QuenMK();
        qmk.setVisible(true);
        qmk.pack();
        qmk.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed
     
    private String getAccountName(String email) {
         Connect_DB cn = new Connect_DB();
        try {
            Connection conn = cn.getConnection();
            // Truy vấn cơ sở dữ liệu để lấy tên tài khoản
            String query = "SELECT Ten FROM TaiKhoan WHERE Email = ?";
            PreparedStatement statement = conn.prepareCall(query);
            statement.setString(1, email);
            ResultSet resultSet = statement.executeQuery();
            resultSet.next();
            return resultSet.getString("Ten");
        } catch (SQLException e) {
        }
        return "";
    }
    /**
     * @param args the command line arguments
     */
    
    public static void main(String[] args){
        java.awt.EventQueue.invokeLater(new Runnable(){
            @Override
            public void run() {
               new LoginForm().setVisible(true) ;
            }
            
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DangNhap;
    private javax.swing.JTextField EmailTxT;
    private javax.swing.JPanel Left;
    private javax.swing.JPasswordField PassTxT;
    private javax.swing.JPanel Right;
    private javax.swing.JButton btnQuaDangKy;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
