/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LoginAndRegister;

import Database.Connect_DB;
import TrangHome.ToanCuc;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class QuenMK extends javax.swing.JFrame {

    /**
     * Creates new form QuenMK
     */
    public QuenMK() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        right = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        DatLaiMK = new javax.swing.JButton();
        TroVeTrangLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(800, 500));
        bg.setLayout(null);

        right.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(56, 161, 222));
        jLabel3.setText("Đặt lại mật khẩu");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Email:");

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        DatLaiMK.setBackground(new java.awt.Color(56, 161, 222));
        DatLaiMK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DatLaiMK.setForeground(new java.awt.Color(255, 255, 255));
        DatLaiMK.setText("Đặt lại");
        DatLaiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatLaiMKActionPerformed(evt);
            }
        });

        TroVeTrangLogin.setBackground(new java.awt.Color(56, 161, 222));
        TroVeTrangLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TroVeTrangLogin.setForeground(new java.awt.Color(255, 255, 255));
        TroVeTrangLogin.setText("Trở về");
        TroVeTrangLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TroVeTrangLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rightLayout = new javax.swing.GroupLayout(right);
        right.setLayout(rightLayout);
        rightLayout.setHorizontalGroup(
            rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightLayout.createSequentialGroup()
                .addGroup(rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(rightLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(DatLaiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(TroVeTrangLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(97, 97, 97))
        );
        rightLayout.setVerticalGroup(
            rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addGap(66, 66, 66)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DatLaiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TroVeTrangLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(171, Short.MAX_VALUE))
        );

        bg.add(right);
        right.setBounds(180, 0, 400, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 77, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DatLaiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatLaiMKActionPerformed

        Connect_DB cn = new Connect_DB();
        
        int avatar = 0;
        try{
            Connection conn = (Connection) cn.getConnection();
            if(txtEmail.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Bạn phải nhập đủ thông tin");
                //Xét điều kiện nếu txt trống thì báo lỗi lên
            }
            else{
                String myemail = txtEmail.getText();
                String email = "@gmail.com";
                if(!myemail.endsWith(email))
                {
                    JOptionPane.showMessageDialog(this,"Email nhập phải có dạng example@gmail.com");
                }
                else{
                    int atIndex = myemail.indexOf(email);
                    if(atIndex >= 0){
                        String userName = myemail.substring(0, atIndex);
                        if(userName.isEmpty()){
                            JOptionPane.showMessageDialog(this,"Email bạn nhập không hợp lệ");
                        }
                        else{
                          
                                        String sql = "select Email from TaiKhoan where Email='"+txtEmail.getText()+"'";
                                        PreparedStatement statement = (PreparedStatement) conn.prepareCall(sql);
                                        ResultSet resultSet = statement.executeQuery();
                                        if (resultSet.next()) {
                                            this.setVisible(false);
                                            this.dispose();
                                            ResetPass re = new ResetPass(); 
                                            re.setVisible(true);
                                            ToanCuc tt = new ToanCuc();
                                            tt.setEmail(txtEmail.getText());
                                            
                                            conn.close();
                                        }
                                        else{
                                            JOptionPane.showMessageDialog(this, "Email không tồn tại");
                                        }
                                 
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Email bạn nhập không hợp lệ");
                    }

                }

            }
        } catch(Exception ex){
            // Handle database errors
            JOptionPane.showMessageDialog(this, "Lỗi khi đăng ký tài khoản: " + ex.getMessage());
        }
    }//GEN-LAST:event_DatLaiMKActionPerformed

    private void TroVeTrangLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TroVeTrangLoginActionPerformed
        // TODO add your handling code here:
        LoginForm login = new LoginForm();
        login.setVisible(true);
        login.pack();
        login.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_TroVeTrangLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuenMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuenMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuenMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuenMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuenMK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DatLaiMK;
    private javax.swing.JButton TroVeTrangLogin;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel right;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
